### ISSUE TITLE
Build help files

### ISSUE THREAD

**Issue by Jacintin** [biolab/orange3-example-addon#10]
Hello,
(sorry, I'm french, I don't speak english)
I am looking to display help files from my personal widgets.
I can not do it.
I also installed this example (orange3-example-addon), all by myself, but the only documentation that works is http://orange3-example-addon.readthedocs.io/en/latest/
I can not display the documentation I made with Sphinx.
3 days of research, testing in every way ... I can not do it!
Thanks for reading me.

**Comment by markotoplak** [comment]
Do you want that documentation works locally? If so, you need to run "make htmlhelp" in doc/ folder.

If you want that it is taken from the web, modify `orangecontrib/example/widgets/__init__.py` accordingly.

Or did you try both of these already and there are some other issues?

**Comment by Jacintin** [comment]
Of course, I tried all the possibilities:
- make html,
- make htmlhelp
I also launched an html server locally with my documentation pages: it works.
In __init__.py, I wrote 3 possibilities:
- (a) the absolute path
- (b) The path with {DEVELOP_ROOT}
- (c) The url to my local server
WIDGET_HELP_PATH = (
     ("{DEVELOP_ROOT} /doc/_build/htmlhelp/index.html", None),
     ("P: /Orange/doc/_build/htmlhelp/index.html", None),
     ("http: // localhost /", "")
)
I tried (a), then (b), then (c), then (a)+(b), then (a)+(c), then (b)+(c), then (a)+(b)+(c)
Always nothing !
Does it work for you?

**Comment by markotoplak** [comment]
I tried myself and as you said, Orange did not properly parse the documentation that was build. Then I added `smartquotes = False` to the end of `doc/conf.py` and after rebuilding the documentation it worked! Could you try the same and report if it works? Thanks you.

I think there is a problem with how Orange parses the documentation. It seems that it does not use the right encoding: it always uses utf-8, but HTML help is build with some other encoding.

**Comment by Jacintin** [comment]
Hello and thank you for your dedication.

I tested but it does not work.
I think you did not understand me because I do not speak correctly.

You say: "Orange did not properly parse the documentation that was build".
In fact, it's not that: to analyze it you must first find it!
But Orange does not find it. The problem is upstream.

I detail you step by step what I did by taking your example and injecting my own documentation.
I also include an image of the final result.

1 - https://github.com/biolab/orange3-example-addon: download zip.
2 - Dezip - renamed and copied folder: P:\Exemple
3 - Completely empty the doc folder
4 - Terminal in P:\Exemple\doc -> run sphinx-quickstart
	- Separate source and build: yes
	- Project name: Exemple
	- Author name: Jacinto
	- Project release: v1.0.0
	- Project language: fr
		|_ Answer -> Finished: An initial directory structure has been created.
5 - P:\Exemple\doc\source\conf.py: add at the end -> smartquotes = False
6 - Terminal in P:\Exemple\doc -> run make htmlhelp
		|_ Answer: You can now run HTML Help Workshop with the .htp file in build\htmlhelp.
7 - Page in P:\Exemple\doc\build\htmlhelp\index.html <- Works
8 - P:\Exemple\orangecontrib\example\widgets\__ init__.py -> WIDGET_HELP_PATH modified
		WIDGET_HELP_PATH = (
		    ("{DEVELOP_ROOT}/doc/build/htmlhelp/index.html", None),
		    ("P:/Exemple/doc/build/htmlhelp/index.html", None),
		)
9 - Terminal in P:\Exemple: run pip install -e .
		|_ Answer: Successfully installed Orange3-Example-Add-on
		|_ pip list => Orange3-Example-Add-on 0.0.3 	p:\exemple
10 - Launch Orange: Error reading the widget doc.
		|_ (image in attached file)
![erreur](https://user-images.githubusercontent.com/8993123/60817418-e675e680-a19b-11e9-933d-0dd9de4016e3.png)

**Comment by astaric** [comment]
Please confirm that:
1. In your index.html file, there is a section called Widgets (div tag with id widgets)
2. Inside this section, there is a list (one or more <li> tags) with links (<a> tags), where link text exactly matches the name of the widget

you can find the code that does the parsing here:
https://github.com/biolab/orange-canvas-core/blob/master/orangecanvas/help/provider.py#L218

**Comment by markotoplak** [comment]
You write very clearly and I understand you well. I was not clear: what I meant with wrong parsing was that Orange is was unable to parse documentation index. Adding `smartquotes` = False fixed it for me.

Please do not empty the doc folder yourself and do not rum `sphinx-quickstart`. Start with the documentation given and when it will work, you can start to change it. What I did just now:

1. Download zip, unzip, move to the folder.
2. cd doc
3. Edit "conf.py", add `smartquotes = False`
4. make htmlhelp
5. cd ..
6. pip install -e .

This works for me. Just tested. The documentation shows up correctly.

When you get it working, make sure that in the future you add new widgets to the index.rst file's section "Widgets" for the documentation to work. In the example add-on its contents are

```
Widgets
-------

.. toctree::
   :maxdepth: 1

   widgets/mywidget
```

When you will add new widgets, you will need to put them there. The name "Widgets" will have to stay in english.

**Comment by Jacintin** [comment]
Indeed, I should not have empty the doc file.
I did this because I had errors in creating the doc.
The recommonmark module was not installed! :(
By following your instructions, it works.
Thank you, thank you ... and thank you!
