### ISSUE TITLE
add my add-on to orange

### ISSUE THREAD

**Issue by ablezhh** [biolab/orange3-example-addon#12]
must i start my add-on through orders like "python -m Orange.canvas"?
i try to operate my orange without orders, but i cannot find my add-ons on the canvas.
what can i do ?
thank u so much !!

**Comment by FruitfulApproach** [comment]
Are you using binary or pip installed version?

**Comment by markotoplak** [comment]
It seems that you have multiple Orange (and python) installations on your computer.  You have to install the add-on into the same python that your Orange canvas (the one you run with a shortcut) is using. How to do this in a command line depends on your installation.

The easiest and most general way is to use the Orange's add-on dialog for installation. First, create you add-on package (`python setup.py sdist`) and then drag the package file onto the add-on dialog window (we sometimes use this for testing).
