### ISSUE TITLE
Some add-ons load other do not in version 3.15

### ISSUE THREAD

**Issue by SImon-Che** [biolab/orange3-example-addon#7]
Some add-ons load other do not in version 3.15
Since upgrading a couple of weeks ago to v3.15 some addons load and others failed. I have tried using console and depending on add-on see different failure messages for the ones that do not load
thanks
Simon Chenery
British Geological Survey

**Comment by BlazZupan** [comment]
@SImon-Che, could you please post the error message. You have posted this issue under a repository for example add-on. What other add-ons are you referring to?

**Comment by flave95** [comment]
Greetings,
i have an issue with installing the example add-on.

"Command "python setup.py egg_info" failed with error code 1 in C:\Users\Admin\AppData\Local\Temp\pip-build-_qceabf0\bottleneck"

It´s always the same issue. I tried it now on 2 Computers and both times used the same Python which comes along with the organge classic installer (Orange3-3.15.0-Python34-win32.exe )

**Comment by acopar** [comment]
This error is most likely caused by a missing or an incompatible compiler. Can you try installing Orange from [Miniconda installer](https://orange.biolab.si/download/files/Orange3-3.16.0-Miniconda-x86_64.exe), and then install the add-ons?
